version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/mosaicod" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/mosaico-sdk-py"
    schedule:
      interval: "weekly"
