site_name: Mosaico Documentation
site_url: https://mosaico.dev/doc
repo_url: https://github.com/mosaico-labs/mosaico

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - typeset
  - mkdocstrings:
      handlers:
        python:
          paths: [../mosaico-sdk-py/src] 
          options:
            filters:
              - "!^__"           
              - "^__init__$"     
              - "!^_"         
            show_root_heading: true
            separate_signature: true     
            merge_init_into_class: true 
            show_source: false

nav:
  - Mosaico: index.md
  - Getting Started:
    - getting_started/mosaicod.md
    - getting_started/python-sdk.md
  - SDK:
    - SDK/index.md
    - SDK/client.md
    - SDK/ontology.md
    - SDK/data-handling.md
    - SDK/query.md
    - Bridges:
        - SDK/bridges/ml.md
    - API Reference:
      - SDK/API_reference/comm.md
      - SDK/API_reference/ml.md
  - Daemon:
    - daemon/index.md
    - daemon/control.md
    - daemon/ingestion.md
    - daemon/query.md
    - daemon/retrieval.md

extra_css:
  - stylesheets/extra.css

extra:
  generator: false

theme:
  logo: assets/mosaico_logomark.svg
  favicon: assets/favicon.svg
  name: material
  font:
    text: Manrope
  palette: 
    scheme: slate
    primary: custom
    accent: light blue
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
  
